name: minepi-server
services:
  mc-server:
    container_name: minecraft-server
    environment:
      ENABLE_AUTOPAUSE: "true"
      ENABLE_ROLLING_LOGS: "true"
      EULA: "TRUE"
      GID: "1000"
      ICON: /data/icon.png
      MEMORY: 6G
      MODRINTH_FORCE_SYNCHRONIZE: "true"
      MODRINTH_LOADER: fabric
      MODRINTH_MODPACK: cobblemon-fabric
      OVERRIDE_ICON: "true"
      PROJECT_ID: 5FFgwNNP
      TYPE: MODRINTH
      UID: "1000"
      VERSION: 1.21.1
    image: itzg/minecraft-server:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 25565
        published: "25565"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /home/clamytoe/minecraft-server/data
        target: /data
        bind:
          create_host_path: true
networks:
  default:
    name: minepi-server_default
